Wyznacz rekurencyjnie wyznacznik dowolnie dużej macierzy.

In [5]:
 # pomocnicza podmacierz

 def subm(mx, c):
    buff = [[1] * len(mx) for i in range(len(mx))]
    for i in range(len(mx)):
        for j in range(len(mx)):
            buff[i][j] = mx[i][j]
    buff.pop(0)
    for i in range(len(buff)):
        buff[i].pop(c)
    return buff

In [6]:
# obliczanie wyznacznika

def det(mx):
    x = 0
    if len(mx) <= 2:
        return mx[0][0] * mx[1][1] - mx[0][1] * mx[1][0]
    else:
        for i in range(len(mx)):
            x += ((-1) ** i) * mx[0][i] * det(subm(mx, i))
    return x.round(3)

In [7]:
import numpy as np
N = int(input("Podaj rozmiar macierzy: "))

np.random.seed(0)
matrix = np.random.uniform(low=0.0, high=10.0, size=(N,N)).round(2)
print(matrix)

det(matrix)

[[5.49 7.15 6.03 5.45 4.24]
 [6.46 4.38 8.92 9.64 3.83]
 [7.92 5.29 5.68 9.26 0.71]
 [0.87 0.2  8.33 7.78 8.7 ]
 [9.79 7.99 4.61 7.81 1.18]]


964.39